### ISSUE TITLE
Variable is always quoted

### ISSUE THREAD

**Issue by boardstretcher** [bbugyi200/cookie#6]
So basically,. it seems that the variable substitution is always adding quotes, whether they are needed or allowed in the resulting config file or not. That's not ideal.

The template
```
.cookiecutter/template.yml
--- # yaml file, that does not need quotes around variables
    variable: {{ VARIABLE }}

```
The input
```
cookie -T template.yml -f my.yml
>>> Found matching template: template.yml
>>> Initializing the '/root/my.yml' script.
VARIABLE: typed_input
```

The output
```
--- # yaml file, that does not need quotes around variables
    variable: "typed_input"

```

**Comment by bbugyi200** [comment]
@boardstretcher Thanks for reporting this. I'm not sure what would have caused that, but I am unable to reproduce it. I've been pushing a lot of commits to this project over the last day, so I may have fixed this without trying to. I tried to reproduce this on a flurry of different commits though, so I'm skeptical.

Can you try to reinstall and retest? If that doesn't work perhaps your editor has a plugin that is doing this? You can test for that by running `EDITOR=: cookie -T template.yaml -f my.yml` and then running `cat my.yml` to check the file.

If none of that works, could you provide your OS, bash version, and what shell your using (shouldn't matter but just in case).

**Comment by bbugyi200** [comment]
I'm going to close this issue since I believe this to be resolved.

If the issue persists, let me know and I will reopen this.
